version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    environment:
      - NATS_SERVER_NAME=nats-server
      - NATS_CLUSTER_PORT=6222
      - NATS_HTTP_PORT=8222

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_MULTIPLE_DATABASES: users, products, orders, payment, storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./docker/pg-init-scripts/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh