scalar JSON

type Query {
  AssetsQuery: AssetsStorageQuery
}

type AssetsStorageQuery {
  getAssetById(assetId: String!): Asset
  getAssetsByUser(userId: String!): [Asset!]!
  getAssetsByCategory(category: String!): [Asset!]!
}

type Asset {
  id: String!
  name: String!
  description: String
  fileKey: String!
  bucketName: String!
  fileSize: Int!
  fileType: String!
  uploadDate: String!
  updatedAt: String!
  tags: [String!]!
  ownerId: String!
  publicAccess: Boolean!
  thumbnailUrl: String
  metadata: JSON
}