scalar Upload
scalar JSON

type Query {
  AssetsQuery: AssetsStorageQuery
}

type AssetsStorageQuery {
  getFileByUserId(input: GetFileByUserIdDto!): FileOutput!
  getFileByUserIdAndFileName(input: GetFileByUserIdAndFileNameDto!): FileOutput!
  getFileByFileId(id: String!): AssetOutput!
  getAllFilesInDatabase: [AssetOutput!]!
  getAllFileNamesInDatabase: [String!]!
}

input GetFileByUserIdDto {
  category: String!
  userId: String!
}

input GetFileByUserIdAndFileNameDto {
  category: String!
  userId: String!
  fileName: String!
}

type AssetOutput {
  id: String!
  file: [String!]!
  titleName: String!
  name: String!
  description: String
  category: String!
  tags: [String!]!
  ownerId: String!
  publicAccess: Boolean
  createdAt: String
  updatedAt: String
}

type Asset {
  id: String!
  file: Upload!
  titleName: String!
  name: String!
  description: String
  category: String!
  tags: [String!]!
  ownerId: String!
  publicAccess: Boolean
  createdAt: String
  updatedAt: String
}

type FileOutput {
  Body: String!
}