scalar JSON
scalar Upload

type Mutation {
  AssetsMutation: AssetsStorageMutation
}

type AssetsStorageMutation {
  createAsset(data: CreateAssetInput!): Boolean!
  updateAsset(data: UpdateAssetInput!): Boolean!
  deleteAsset(assetId: String!): Boolean!
}

input CreateAssetInput {
  file: Upload!
  name: String!
  description: String
  category: String!
  fileKey: String!
  bucketName: String!
  fileSize: Int!
  fileType: String!
  tags: [String!]!
  ownerId: String!
  publicAccess: Boolean
  thumbnailUrl: String
  metadata: JSON
}

input UpdateAssetInput {
  id: String!
  name: String
  description: String
  category: String!
  fileKey: String
  bucketName: String
  fileSize: Int
  fileType: String
  tags: [String!]
  ownerId: String
  publicAccess: Boolean
  thumbnailUrl: String
  metadata: JSON
}