scalar Upload
scalar JSON

type Query {
  AssetsQuery: AssetsStorageQuery
}

type AssetsStorageQuery {
  getFileByUserId(input: GetFileByUserIdDto!): FileOutput!
  getFileByUserIdAndFileName(input: GetFileByUserIdAndFileNameDto!): FileOutput!
}

input GetFileByUserIdDto {
  category: String!
  userId: String!
}

input GetFileByUserIdAndFileNameDto {
  category: String!
  userId: String!
  fileName: String!
}

type Asset {
  file: Upload!
  id: String!
  name: String!
  description: String
  category: String!
  fileKey: String!
  bucketName: String!
  fileSize: Int!
  fileType: String!
  uploadDate: String!
  updatedAt: String!
  tags: [String!]!
  ownerId: String!
  publicAccess: Boolean!
  thumbnailUrl: String
  metadata: JSON
}

type FileOutput {
  Body: String!
}