type Mutation {
  Auth: AuthMutation
}

type AuthMutation {
  register(data: UserRegisterInput!): AuthPayload!
  login(data: UserLoginInput!): AuthPayload!
  deleteAccount(email: String!): Boolean!
}

input UserRegisterInput {
  email: String!
  username: String!
  password: String!
}

input UserLoginInput {
  email: String!
  password: String!
}

type TokenResponse {
  accessToken: String!
}

type AuthPayload {
  accessToken: String!
  user: User!
}

type User {
  id: ID!
  username: String!
  email: String!
}