type Mutation {
  Auth: AuthMutation
}

type AuthMutation {
  register(data: UserRegisterInput!): TokenResponse!
  login(data: UserLoginInput!): TokenResponse!
  deleteAccount(email: String!): Boolean!
}

input UserRegisterInput {
  email: String!
  username: String!
  password: String!
}

input UserLoginInput {
  email: String!
  password: String!
}
type TokenResponse {
  accessToken: String!
}

type AuthPayload {
  token: String!
  user: User!
}